name: Trigger auto deployment for api-reservas-sif

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/api-reservas-sif-AutoDeployTrigger-201a05f1-19f1-411e-b0c6-945734b2cfed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APIRESERVASSIF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APIRESERVASSIF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APIRESERVASSIF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.APIRESERVASSIF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APIRESERVASSIF_REGISTRY_PASSWORD }}
          containerAppName: api-reservas-sif
          resourceGroup: SIF
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


